name: test-OpsDev-CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches : [main]
  pull_request:
    branches : [main]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker image
      run: docker build . --file Dockerfile --tag bhuang02/opsdev-calculator
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: push to Docker repo
      run: docker push bhuang02/opsdev-calculator:latest
      
